import type { Metadata } from "next";
import ChatContext from "./context";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AddToLayoult from "./client";
import Header from "./basic/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
   {
  children
}: Readonly<{
  children?: React.ReactNode;
}>

) {
  return (
<AddToLayoult>
  
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></link>
        <meta name="viewport" content="width=device-width, initial-scale=1"/> 
        <title>Мій сайт</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

      {children}
      </body>
    </html>
    </AddToLayoult>
  );
}
